use world
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/achievement_reward_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/broadcast_text_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/creature_template_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/creature_template.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/creature_text_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/gameobject_template_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/gossip_menu_option_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/item_set_names_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/item_template_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/npc_text_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/page_text_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/points_of_interest_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/quest_template_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/quest_request_items_locale.sql
source E:/OtherProjects/TrinityCore/wowdb-zh-master/zhCN/quest_offer_reward_locale.sql